version: '3'
services:
  fastapi:
    build:
      context: ./cnuchatbot-fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - ./cnuchatbot-fastapi:/usr/src/cnuchatbot-fastapi
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - fastapi